name: real_state_finder
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  flutter_tts: ^3.2.2
  geolocator: ^7.4.0
  http: ^0.13.3
  wakelock: ^0.5.3+3
  # flutter_geocoder: ^0.2.2-nullsafety
  hive: ^2.0.4
  path_provider: ^2.0.3
  finance: ^0.1.0 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/image/